Grupo 5

Anderson Stick Barrera Tovar

Lizeth Mariana García Duarte

Diego Felipe Benitez Cely

# PLU SymPy

In [1]:
from sympy import Matrix,init_printing, eye, zeros
init_printing()

In [2]:
import sympy
import numpy as np
def PLU(A,k):
    U = A.copy()
    shape_a = U.shape
    n = shape_a[0]
    L = np.eye(n)
    P = np.eye(n)
    for i in range(n):
        k = i
        comp = abs(U[i, i])
        for j in range(i, n):
            if abs(U[j, i]) > comp:
                k = j
                comp = abs(U[j, i])
        line_u = U[k, :].copy()
        U[k, :] = U[i, :]
        U[i, :] = line_u
        line_p = P[k, :].copy()
        P[k, :] = P[i, :]
        P[i, :] = line_p
        for j in range(i + 1, n):
            g = U[j, i] / U[i, i]
            L[j, i] = g
            U[j, :] -= g * U[i, :]
    return L, U, P


In [3]:
A = Matrix([[-2,2,-1], [6,-6,7], [3,-8,4]])
A

⎡-2  2   -1⎤
⎢          ⎥
⎢6   -6  7 ⎥
⎢          ⎥
⎣3   -8  4 ⎦

In [4]:
P,L,U = PLU(A,0)

In [5]:
P

array([[ 1.        ,  0.        ,  0.        ],
       [-0.33333333,  1.        ,  0.        ],
       [ 0.5       ,  0.        ,  1.        ]])

In [6]:
L

⎡6  -6   7 ⎤
⎢          ⎥
⎢0  -5  1/2⎥
⎢          ⎥
⎣0  0   4/3⎦

In [7]:
U

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [8]:
P,L,U = PLU(A,1)

In [9]:
P

array([[ 1.        ,  0.        ,  0.        ],
       [-0.33333333,  1.        ,  0.        ],
       [ 0.5       ,  0.        ,  1.        ]])

In [10]:
L

⎡6  -6   7 ⎤
⎢          ⎥
⎢0  -5  1/2⎥
⎢          ⎥
⎣0  0   4/3⎦

In [11]:
U

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [12]:
P,L,U = PLU(A,2)

In [ ]:
P

array([[ 1.        ,  0.        ,  0.        ],
       [-0.33333333,  1.        ,  0.        ],
       [ 0.5       ,  0.        ,  1.        ]])

In [13]:
L

⎡6  -6   7 ⎤
⎢          ⎥
⎢0  -5  1/2⎥
⎢          ⎥
⎣0  0   4/3⎦

In [14]:
U

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [15]:
from sympy import  N
N(U)

AttributeError: ignored

In [16]:
# Now, generate a full rank matrix and test the naive implementation

import sympy
import numpy as np

N = 6
A = sympy.zeros(N)
for i in range(N):
    for j in range(N):
        A[i, j] = 2 + sympy.Rational(1,i*j+1)

A

⎡3   3     3     3     3     3  ⎤
⎢                               ⎥
⎢3  5/2   7/3   9/4   11/5  13/6⎥
⎢                               ⎥
⎢                            23 ⎥
⎢3  7/3   11/5  15/7  19/9   ── ⎥
⎢                            11 ⎥
⎢                               ⎥
⎢                21    27    33 ⎥
⎢3  9/4   15/7   ──    ──    ── ⎥
⎢                10    13    16 ⎥
⎢                               ⎥
⎢                27    35    43 ⎥
⎢3  11/5  19/9   ──    ──    ── ⎥
⎢                13    17    21 ⎥
⎢                               ⎥
⎢          23    33    43    53 ⎥
⎢3  13/6   ──    ──    ──    ── ⎥
⎣          11    16    21    26 ⎦

In [17]:
np.array(A).astype(np.float64)

array([[3.        , 3.        , 3.        , 3.        , 3.        ,
        3.        ],
       [3.        , 2.5       , 2.33333333, 2.25      , 2.2       ,
        2.16666667],
       [3.        , 2.33333333, 2.2       , 2.14285714, 2.11111111,
        2.09090909],
       [3.        , 2.25      , 2.14285714, 2.1       , 2.07692308,
        2.0625    ],
       [3.        , 2.2       , 2.11111111, 2.07692308, 2.05882353,
        2.04761905],
       [3.        , 2.16666667, 2.09090909, 2.0625    , 2.04761905,
        2.03846154]])

In [18]:
np.linalg.matrix_rank(np.array(A).astype(np.float64))

6

In [19]:
A[1, 1] = 3

In [20]:
A

⎡3   3     3     3     3     3  ⎤
⎢                               ⎥
⎢3   3    7/3   9/4   11/5  13/6⎥
⎢                               ⎥
⎢                            23 ⎥
⎢3  7/3   11/5  15/7  19/9   ── ⎥
⎢                            11 ⎥
⎢                               ⎥
⎢                21    27    33 ⎥
⎢3  9/4   15/7   ──    ──    ── ⎥
⎢                10    13    16 ⎥
⎢                               ⎥
⎢                27    35    43 ⎥
⎢3  11/5  19/9   ──    ──    ── ⎥
⎢                13    17    21 ⎥
⎢                               ⎥
⎢          23    33    43    53 ⎥
⎢3  13/6   ──    ──    ──    ── ⎥
⎣          11    16    21    26 ⎦

In [21]:
np.linalg.matrix_rank(np.array(A).astype(np.float64))

6

In [22]:
P,L,U = PLU(A,0)

In [ ]:
P

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.8       , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.9       , 0.05844156, 1.        , 0.        ,
        0.        ],
       [1.        , 0.96      , 0.02424242, 0.19329389, 1.        ,
        0.        ],
       [1.        , 0.        , 0.10909091, 0.49038462, 0.61136249,
        1.        ]])

In [23]:
L

⎡3   3     3     3      3        3    ⎤
⎢                                     ⎥
⎢         -10   -15    -20      -25   ⎥
⎢0  -5/6  ────  ────   ────     ────  ⎥
⎢          11    16     21       26   ⎥
⎢                                     ⎥
⎢0   0    -2/3  -3/4   -4/5     -5/6  ⎥
⎢                                     ⎥
⎢               -39   -688            ⎥
⎢0   0     0    ────  ─────    -7/143 ⎥
⎢               1540  17325           ⎥
⎢                                     ⎥
⎢                               123   ⎥
⎢0   0     0     0    2/6825   ────── ⎥
⎢                              208208 ⎥
⎢                                     ⎥
⎢                               -32   ⎥
⎢0   0     0     0      0     ────────⎥
⎣                             25882857⎦

In [24]:
U

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [25]:
P,L,U = PLU(A,1)

In [26]:
P

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.8       , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.9       , 0.05844156, 1.        , 0.        ,
        0.        ],
       [1.        , 0.96      , 0.02424242, 0.19329389, 1.        ,
        0.        ],
       [1.        , 0.        , 0.10909091, 0.49038462, 0.61136249,
        1.        ]])

In [27]:
L

⎡3   3     3     3      3        3    ⎤
⎢                                     ⎥
⎢         -10   -15    -20      -25   ⎥
⎢0  -5/6  ────  ────   ────     ────  ⎥
⎢          11    16     21       26   ⎥
⎢                                     ⎥
⎢0   0    -2/3  -3/4   -4/5     -5/6  ⎥
⎢                                     ⎥
⎢               -39   -688            ⎥
⎢0   0     0    ────  ─────    -7/143 ⎥
⎢               1540  17325           ⎥
⎢                                     ⎥
⎢                               123   ⎥
⎢0   0     0     0    2/6825   ────── ⎥
⎢                              208208 ⎥
⎢                                     ⎥
⎢                               -32   ⎥
⎢0   0     0     0      0     ────────⎥
⎣                             25882857⎦

In [28]:
U

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [29]:
P,L,U = PLU(A,2)

In [30]:
P

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.8       , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.9       , 0.05844156, 1.        , 0.        ,
        0.        ],
       [1.        , 0.96      , 0.02424242, 0.19329389, 1.        ,
        0.        ],
       [1.        , 0.        , 0.10909091, 0.49038462, 0.61136249,
        1.        ]])

In [31]:
L

⎡3   3     3     3      3        3    ⎤
⎢                                     ⎥
⎢         -10   -15    -20      -25   ⎥
⎢0  -5/6  ────  ────   ────     ────  ⎥
⎢          11    16     21       26   ⎥
⎢                                     ⎥
⎢0   0    -2/3  -3/4   -4/5     -5/6  ⎥
⎢                                     ⎥
⎢               -39   -688            ⎥
⎢0   0     0    ────  ─────    -7/143 ⎥
⎢               1540  17325           ⎥
⎢                                     ⎥
⎢                               123   ⎥
⎢0   0     0     0    2/6825   ────── ⎥
⎢                              208208 ⎥
⎢                                     ⎥
⎢                               -32   ⎥
⎢0   0     0     0      0     ────────⎥
⎣                             25882857⎦

In [32]:
U

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [33]:
P,L,U = PLU(A,3)

In [34]:
P

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.8       , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.9       , 0.05844156, 1.        , 0.        ,
        0.        ],
       [1.        , 0.96      , 0.02424242, 0.19329389, 1.        ,
        0.        ],
       [1.        , 0.        , 0.10909091, 0.49038462, 0.61136249,
        1.        ]])

In [35]:
L

⎡3   3     3     3      3        3    ⎤
⎢                                     ⎥
⎢         -10   -15    -20      -25   ⎥
⎢0  -5/6  ────  ────   ────     ────  ⎥
⎢          11    16     21       26   ⎥
⎢                                     ⎥
⎢0   0    -2/3  -3/4   -4/5     -5/6  ⎥
⎢                                     ⎥
⎢               -39   -688            ⎥
⎢0   0     0    ────  ─────    -7/143 ⎥
⎢               1540  17325           ⎥
⎢                                     ⎥
⎢                               123   ⎥
⎢0   0     0     0    2/6825   ────── ⎥
⎢                              208208 ⎥
⎢                                     ⎥
⎢                               -32   ⎥
⎢0   0     0     0      0     ────────⎥
⎣                             25882857⎦

In [36]:
U

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [37]:
P,L,U = PLU(A,4)

In [38]:
P

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.8       , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.9       , 0.05844156, 1.        , 0.        ,
        0.        ],
       [1.        , 0.96      , 0.02424242, 0.19329389, 1.        ,
        0.        ],
       [1.        , 0.        , 0.10909091, 0.49038462, 0.61136249,
        1.        ]])

In [39]:
L

⎡3   3     3     3      3        3    ⎤
⎢                                     ⎥
⎢         -10   -15    -20      -25   ⎥
⎢0  -5/6  ────  ────   ────     ────  ⎥
⎢          11    16     21       26   ⎥
⎢                                     ⎥
⎢0   0    -2/3  -3/4   -4/5     -5/6  ⎥
⎢                                     ⎥
⎢               -39   -688            ⎥
⎢0   0     0    ────  ─────    -7/143 ⎥
⎢               1540  17325           ⎥
⎢                                     ⎥
⎢                               123   ⎥
⎢0   0     0     0    2/6825   ────── ⎥
⎢                              208208 ⎥
⎢                                     ⎥
⎢                               -32   ⎥
⎢0   0     0     0      0     ────────⎥
⎣                             25882857⎦

In [40]:
U

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [41]:
P,L,U = PLU(A,5)

In [42]:
P

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.8       , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.9       , 0.05844156, 1.        , 0.        ,
        0.        ],
       [1.        , 0.96      , 0.02424242, 0.19329389, 1.        ,
        0.        ],
       [1.        , 0.        , 0.10909091, 0.49038462, 0.61136249,
        1.        ]])

In [43]:
L

⎡3   3     3     3      3        3    ⎤
⎢                                     ⎥
⎢         -10   -15    -20      -25   ⎥
⎢0  -5/6  ────  ────   ────     ────  ⎥
⎢          11    16     21       26   ⎥
⎢                                     ⎥
⎢0   0    -2/3  -3/4   -4/5     -5/6  ⎥
⎢                                     ⎥
⎢               -39   -688            ⎥
⎢0   0     0    ────  ─────    -7/143 ⎥
⎢               1540  17325           ⎥
⎢                                     ⎥
⎢                               123   ⎥
⎢0   0     0     0    2/6825   ────── ⎥
⎢                              208208 ⎥
⎢                                     ⎥
⎢                               -32   ⎥
⎢0   0     0     0      0     ────────⎥
⎣                             25882857⎦

In [44]:
U

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [45]:
from sympy import  N
N(U)


AttributeError: ignored